

const MAX_TEMPLATE_ALLOWED = 50;
const MAX_TESTS_ALLOWED = 50;
const MAX_RUNS_ALLOWED = 50;
const MAX_TAGS_ALLOWED = 200;
const MAX_STUDENTS_ALLOWED = 25;
const MAX_CLASSES_ALLOWED = 15;
const MAX_RESPONSES_ALLOWED = 500;
const MAX_Q_PER_SURVEY = 20;
const MAX_OPT_PER_Q = 200;





module.exports = {
    MAX_TEMPLATE_ALLOWED,    
    MAX_RESPONSES_ALLOWED,
    MAX_Q_PER_SURVEY,
    MAX_OPT_PER_Q,
    MAX_TAGS_ALLOWED,
    MAX_CLASSES_ALLOWED,
    MAX_STUDENTS_ALLOWED,
    MAX_TESTS_ALLOWED,
    MAX_RUNS_ALLOWED
}